services:
  - type: web
    name: unride
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: APP_KEY
        generateValue: true

      # ------------ DATABASE VARS ------------
      - key: DB_CONNECTION
        value: pgsql

      - key: DB_HOST
        value: dpg-d4o8ng63jp1c73f9j1kg-a

      - key: DB_PORT
        value: 5432

      - key: DB_DATABASE
        value: uniridedb

      - key: DB_USERNAME
        value: uniridedb_user

      - key: DB_PASSWORD
        value: 84nwhR7yPjFsudNurj5JhStigCgXRa26

    commands:
      start: |
        php artisan migrate --force
        php artisan db:seed --force
        php-fpm
