services:
  - type: web
    name: unride
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: APP_KEY
        generateValue: true

      # ------------ DATABASE VARS ------------
      - key: DB_CONNECTION
        value: pgsql

      - key: DB_HOST
        value: dpg-d4o8ng63jp1c73f9j1kg-a

      - key: DB_PORT
        value: 5432

      - key: DB_DATABASE
        value: uniridedb

      - key: DB_USERNAME
        value: uniridedb_user

      - key: DB_PASSWORD
        value: 84nwhR7yPjFsudNurj5JhStigCgXRa26

      # ------------ STRIPE VARS ------------
      - key: STRIPE_SECRET
        value: sk_test_51SO3WH339npoHN8QViWhXoA5zDyNdYjovGSd9hhi7mb2HqJ1OLHZMYHWiU9M5RkHJyZVxSI5d0IZtSRB38zSdgnV00PeC9mSxf
    
      - key: STRIPE_KEY
        value: pk_test_51SO3WH339npoHN8Q84X5NCVGpRLHY6IhhM294mZoAkiOW0T1AAyS97VeOT6enSVejcG8FERZYzGAU2rdP0EATIxH00mYdyf2wC

    commands:
      start: |
        php artisan config:clear
        php artisan cache:clear
        php artisan view:clear
        php artisan route:clear
        php artisan config:cache
        php artisan migrate --force
        php artisan db:seed --force
        php-fpm
